### ISSUE TITLE
Failed to activate the vim-mode-plus-exchange package

### ISSUE THREAD

**Issue by jackcasey** [dillonkearns/atom-vim-mode-plus-exchange#4]
Potentially just not compatible with the newest version of VMP 1.9.0 which moved away from coffeescript etc.

1. Install vim mode plus and vim-mode-plus-exchange

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [vim-mode-plus-exchange](https://github.com/dillonkearns/atom-vim-mode-plus-exchange) package 0.2.1

### Stack Trace

Failed to activate the vim-mode-plus-exchange package

```
At Exchange.registerCommand is not a function

TypeError: Exchange.registerCommand is not a function
    at Object.consumeVim (/packages/vim-mode-plus-exchange/lib/main.coffee:18:16)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:50:24)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:454:81)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:256:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:690:42)
    at packagesToEnable.forEach.name (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:439:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:439:30)
    at /Applications/Atom.app/Contents/Resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:248:20)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:407:18)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app/src/package.js:84:32)
    at PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:245:18)
    at Object.proton.lib.atom.enable_package (/packages/proton-mode/lib/proton.js:2460:290)
    at Object.proton.lib.atom.force_reload_package (/packages/proton-mode/lib/proton.js:2465:141)
    at /packages/proton-mode/lib/proton.js:2665:82
```

### Commands

```
     -1:00.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-dark-fusion-syntax 2.2.0 
atom-fuzzy-grep 0.16.0 
atom-material-syntax 1.0.7 
atom-material-ui 2.0.5 
atom-ternjs 0.18.3 
autocomplete-modules 1.7.2 
autoupdate-packages 1.3.1 
blame 0.12.0 
busy 0.7.0 
busy-signal 1.4.3 
cursor-history 0.12.0 
easy-motion-redux 1.1.1 
file-icons 2.1.12 
fonts 3.0.3 
git-history 3.3.0 
git-plus 7.9.3 
golden-ratio 0.3.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-diff 0.7.0 
lines 0.13.1 
linter 2.2.0 
linter-eslint 8.3.2 
linter-jshint 3.1.6 
linter-rubocop 2.2.0 
linter-ruby 1.2.6 
linter-ui-default 1.6.10 
maximize-panes 0.2.0 
move-panes 0.2.0 
narrow 0.52.0 
nucleus-dark-ui 0.12.3 
project-plus 1.0.0 
proton-mode 0.16.0 
quick-highlight 0.11.0 
react 0.16.2 
react-snippets undefined 
recent-files-fuzzy-finder 0.3.2 
release-notes 0.53.0 
rubocop-auto-correct 1.5.1 
ruby-block 0.3.6 
ruby-block-converter 4.0.1 
theme-switch 0.5.0 
vim-mode-plus 1.9.1 
vim-mode-plus-exchange 0.2.1 
zentabs 0.8.8 
```

**Comment by dillonkearns** [comment]
Sorry for the delay, it's working with the latest vmp now!
